listen_addresses = ['0.0.0.0:53']
server_names = ['cloudflare', 'google']

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
  ignored_qtypes = ['DNSKEY', 'NS']

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'

[blocked_names]
  log_file = '/var/log/dnscrypt-proxy/blocked-names.log'

[blocked_ips]
  log_file = '/var/log/dnscrypt-proxy/blocked-ips.log'

[allowed_names]
  log_file = '/var/log/dnscrypt-proxy/allowed-names.log'

[allowed_ips]
  log_file = '/var/log/dnscrypt-proxy/allowed-ips.log'

[sources]
  [sources.'public-resolvers']
  urls = [
    'https://github.com/DNSCrypt/dnscrypt-resolvers/tree/master/v3/public-resolvers.md',
    'https://download.dnscrypt.info/dnscrypt-resolvers/v3//public-resolvers.md',
  ]
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
